# Generated by Django 5.1.7 on 2025-05-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artist_track_remove_album_author_delete_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='path',
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(to='music.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='audio_url',
            field=models.URLField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
