# Generated by Django 5.1.7 on 2025-05-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_track_path_track_artists_track_audio_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='music.album'),
        ),
    ]
