# Generated by Django 5.1.7 on 2025-05-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
