# Generated by Django 5.1.7 on 2025-05-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_track_audio_url_alter_track_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
