# Generated by Django 5.1.7 on 2025-05-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='realease_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
