# Generated by Django 5.1.7 on 2025-05-22 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_track_realease_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='realease_date',
            new_name='release_date',
        ),
    ]
