# Generated by Django 5.1.7 on 2025-05-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_rename_realease_date_track_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
